Disable pull image by default, add force pull option
jlevesy/go-sind pull request #19
Opened 2019-03-19 16:34 UTC by mmatur

### Description

This PR adds a new flag to force pulling image when we create a new sind cluster.

With this PR, sind will pull image if it does not exist on the filesystem or if the flat `pull` is enabled

2019-03-19 17:09 UTC, Ullaakut approved these changes

2019-03-20 07:47 UTC, jlevesy requested changes
Sound good to me, thanks for the contribution !  Few suggestions.

2019-03-20 07:47 UTC, jlevesy commented on pkg/cli/create.go
> +	createCmd.Flags().BoolVarP(&pull, "pull", "", false, "Force pull image.")
```suggestion
	createCmd.Flags().BoolVarP(&pull, "pull", "", false, Pull node image before creating the cluster.")
```

2019-03-20 07:47 UTC, jlevesy commented on pkg/cli/create.go
> +		ForcePull:    pull,
```suggestion
		PullImage:    pull,
```

2019-03-20 07:47 UTC, jlevesy commented on pkg/sind/create.go
> +	ForcePull    bool
```suggestion
	PullImage    bool
```

2019-03-20 07:47 UTC, jlevesy commented on pkg/sind/create.go
> +	if params.ForcePull || !imageExist {
```suggestion
	if params.PullImage || !imageExist {
```

2019-03-20 08:28 UTC, jlevesy approved these changes
LGTM :+1:

2019-03-20 08:29 UTC, merged